### ISSUE TITLE
Scheduled Weigh In reminder 

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#453] opened 2022-05-31 20:35 UTC
Being able to remind clients to input their weight either on a weekly or a monthly rather than daily could be beneficial.

**Comment by alicolville** [comment] 2022-05-31 20:38
Is this to expand https://docs.yeken.uk/shortcodes/wt-reminder.html?

**Comment by YOPT21** [comment] 2022-05-31 21:06
Exactly

**Comment by alicolville** [comment] 2022-09-23 21:35
Closed as a duplicate of #268

**Closed by alicolville** 2022-09-23 21:35 UTC
Labels: enhancement
